import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Masthead from "../components/masthead";
import Bio from "../components/bio";
import Appearance from "../components/appearance";
import Works from "../components/works";
import Telop from "../components/telop";
import ContactUs from "../components/contactus";
import Footer from "../components/footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <Appearance />
      <Bio />
      <Works />
      <Telop />
      <ContactUs />
      <Footer />
    </div>
  );
};

export default Home;
